/* Main entry point for the MIDI Player application
 * Loads FluidSynth WASM, initializes js-synthesizer, and starts the app
 */

// Import CSS
import './styles.css';

// Import auto-detected FluidSynth path (generated by Vite plugin)
import { FLUIDSYNTH_PATH } from './fluidsynth-version.js';

// Load FluidSynth WASM externals
const externalsScript = document.createElement('script');
externalsScript.src = FLUIDSYNTH_PATH;
externalsScript.async = false;
document.head.appendChild(externalsScript);

// Wait for externals to load, then initialize everything
externalsScript.onload = async () => {
  console.log('[Init] FluidSynth WASM loaded');
  
  // Import js-synthesizer and expose globally (needed by synthesizer-player.js)
  window.JSSynth = await import('js-synthesizer');
  console.log('[Init] js-synthesizer loaded');
  
  // Load app modules
  await import('./synthesizer-player.js');
  console.log('[Init] Synthesizer player loaded');
  
  await import('./app.js');
  console.log('[Init] App initialized');
};

externalsScript.onerror = () => {
  console.error('[Init] Failed to load FluidSynth WASM');
  alert('Failed to initialize audio engine. Please refresh the page.');
};
